"""followers

Revision ID: 65236331d7e4
Revises: 1fe41997a92f
Create Date: 2020-09-12 11:53:44.005548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65236331d7e4'
down_revision = '1fe41997a92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
